version: '3.8'

services:
  pygame-game:
    build: .
    container_name: pygame-game
    environment:
      - DISPLAY=${DISPLAY}  
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
    stdin_open: true
    tty: true
